/**
 * i18n-split.mjs — how the i18n modules are cut into a core bundle and lazy
 * chunks, and which pages have an Easy-Language preview. Shared by
 * scripts/build-i18n-bundles.ts (writes the output) and
 * scripts/check-i18n-keys.mjs (fails when the committed availability index is
 * stale), so both apply one rule.
 *
 * Config: src/config/i18n-bundles.json. Runtime side: TranslationService.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const REPO_ROOT = join(fileURLToPath(new URL('.', import.meta.url)), '..', '..');

/** Parent of the per-page Easy-Language previews. */
export const EASY_PREVIEW_PARENT = 'easyLanguage.content';
/** Children of EASY_PREVIEW_PARENT that are not pages (the generic fallback preview). */
const NON_PAGE_PREVIEWS = new Set(['preview']);

/** src/config/i18n-bundles.json, with the lazy patterns compiled. */
export function readSplitConfig(configPath = join(REPO_ROOT, 'src', 'config', 'i18n-bundles.json')) {
  const cfg = JSON.parse(readFileSync(configPath, 'utf-8'));
  const matchers = (cfg.lazyNamespaces ?? []).map((entry) => {
    const re = /^\/(.*)\/$/.exec(entry);
    return re ? (ns) => new RegExp(re[1]).test(ns) : (ns) => ns === entry;
  });
  return {
    isLazy: (ns) => matchers.some((m) => m(ns)),
    coreKeys: [...(cfg.coreKeys ?? [])],
    splitChildren: [...(cfg.splitChildren ?? [])],
  };
}

function getPath(tree, segments) {
  let node = tree;
  for (const s of segments) {
    if (!node || typeof node !== 'object' || !(s in node)) return undefined;
    node = node[s];
  }
  return node;
}

/**
 * Split one locale's modules ({ ns: data }) into { core, chunks }.
 * A lazy namespace becomes chunk `<ns>`, but the `coreKeys` paths inside it are
 * ALSO copied into the core (a chunk is a superset: the runtime merges it over
 * the core copy). Each child of a split parent becomes chunk `<parent>.<child>`
 * and is removed from wherever it would otherwise be.
 */
export function splitLocale(modules, split) {
  const core = {};
  const chunks = {};
  for (const [ns, data] of Object.entries(modules)) {
    if (!split.isLazy(ns)) {
      core[ns] = structuredClone(data);
      continue;
    }
    chunks[ns] = structuredClone(data);
    for (const path of split.coreKeys ?? []) {
      const segments = path.split('.');
      const value = getPath(data, segments);
      if (value === undefined) continue;
      let node = (core[ns] ??= {});
      for (const s of segments.slice(0, -1)) node = node[s] ??= {};
      node[segments[segments.length - 1]] = structuredClone(value);
    }
  }
  for (const parent of split.splitChildren) {
    const segments = parent.split('.');
    const home = split.isLazy(segments[0]) ? chunks : core;
    const holder = getPath(home, segments.slice(0, -1));
    const node = holder?.[segments[segments.length - 1]];
    if (!node || typeof node !== 'object' || Array.isArray(node)) continue;
    for (const [child, value] of Object.entries(node)) chunks[`${parent}.${child}`] = value;
    delete holder[segments[segments.length - 1]];
  }
  return { core, chunks };
}

/**
 * The Easy-Language availability index: the pages (as camelCase ids, the form
 * the preview keys use) that have a preview under `easyLanguage.content` in
 * EVERY locale — the preview is shown in the reader's current language, so a
 * page missing one anywhere does not count. Sorted, so the file is stable.
 */
export function easyAvailabilityFromModules(modulesByLocale) {
  let ids = null;
  for (const modules of modulesByLocale.values()) {
    const node = getPath(modules, EASY_PREVIEW_PARENT.split('.'));
    const here = new Set(node && typeof node === 'object' ? Object.keys(node) : []);
    ids = ids === null ? here : new Set([...ids].filter((id) => here.has(id)));
  }
  return {
    _comment:
      'GENERATED by scripts/build-i18n-bundles.ts from the easyLanguage.content previews in src/assets/i18n/modules — do not edit. A page id (camelCase, e.g. aiTimeline for ai-timeline) is listed when every locale has its preview. EasyLanguageService.hasEasyVersion() reads it.',
    ids: [...(ids ?? [])].filter((id) => !NON_PAGE_PREVIEWS.has(id)).sort(),
  };
}
