/**
 * OntologyService
 *
 * Loads the consolidated, canonical-ordered ontology edge list once per
 * session (language-independent — only IDs are stored) and exposes
 * adjacency-style query methods used by RelatedRefsService and the
 * upcoming OntologyMapComponent.
 *
 * Design: an internal design note.
 */
import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, of, map, shareReplay, catchError, combineLatest } from 'rxjs';
import {
  ConsolidatedOntology,
  ONTOLOGY_NODE_TYPES,
  OntologyEdge,
  OntologyNodeRef,
  OntologyNodeType,
  OntologySubgraph,
  nodeKey,
} from './ontology.types';
import { toObservable } from '@angular/core/rxjs-interop';
import { DemosService } from './demos.service';
import { ArticlesService } from './articles.service';
import { DevModeService } from './dev-mode.service';

interface IndexedOntology {
  edges: OntologyEdge[];
  adjacency: Map<string, OntologyEdge[]>;
  nodeCount: Record<OntologyNodeType, number>;
}

const ONTOLOGY_URL = '/assets/data/ontology/edges.consolidated.json';
const POSITIONS_URL = '/assets/data/ontology/nodes.positions.json';

interface PositionsPayload {
  version?: number;
  generatedAt?: string;
  nodeCount?: number;
  positions: Record<string, { x: number; y: number }>;
}

const EMPTY_ONTOLOGY: IndexedOntology = {
  edges: [],
  adjacency: new Map(),
  nodeCount: { article: 0, demo: 0, glossary: 0, timeline: 0, source: 0 },
};

@Injectable({ providedIn: 'root' })
export class OntologyService {
  private http = inject(HttpClient);
  private demos = inject(DemosService);
  private articles = inject(ArticlesService);
  private devMode = inject(DevModeService);
  private indexed$: Observable<IndexedOntology>;
  private positions$: Observable<Map<string, { x: number; y: number }> | null>;

  /**
   * Node-keys (`<type>:<id>`) of content hidden on the current discovery
   * surface — pre-release demos (future `publishDate`) and draft/scheduled
   * articles. Gated on `DevModeService.isEffectivelyProd` (real prod OR the
   * "simulate prod" UI toggle), NOT on `isDevMode`: flipping the toggle hides
   * scheduled content in the concept-map live, mirroring navigation.service's
   * search. Toggle off ⇒ empty set ⇒ full author preview. The route guard
   * deliberately stays `isDevMode`-based. Glossary/timeline have no draft
   * concept, so they never appear here.
   */
  private excludedKeys$: Observable<Set<string>>;

  constructor() {
    this.excludedKeys$ = combineLatest([
      this.demos.getAllDemos().pipe(catchError(() => of([]))),
      this.articles.getAll().pipe(catchError(() => of([]))),
      toObservable(this.devMode.isEffectivelyProd),
    ]).pipe(
      map(([demos, articles, isProd]) => {
        const excluded = new Set<string>();
        // Dev preview (toggle off): show everything. Real prod or "simulate
        // prod": hide not-yet-released content. Array guards mirror
        // buildIndex's defensiveness — a malformed index must not crash the graph.
        if (!isProd) return excluded;
        if (Array.isArray(demos)) {
          for (const d of demos) if (!this.demos.isPublished(d)) excluded.add(`demo:${d.id}`);
        }
        if (Array.isArray(articles)) {
          for (const a of articles) if (!this.articles.isVisibleInProd(a)) excluded.add(`article:${a.id}`);
        }
        return excluded;
      }),
      shareReplay({ bufferSize: 1, refCount: false }),
    );

    this.indexed$ = combineLatest([
      this.http.get<ConsolidatedOntology>(ONTOLOGY_URL).pipe(
        catchError((err) => {
          console.warn('[OntologyService] failed to load consolidated edges — graph empty.', err);
          return of(null);
        }),
      ),
      this.excludedKeys$,
    ]).pipe(
      map(([payload, excluded]) => this.buildIndex(payload, excluded)),
      shareReplay({ bufferSize: 1, refCount: false }),
    );
    // Pre-computed fcose layout. Optional — if the file is missing, the map
    // falls back to running fcose live. Generated by
    // `node scripts/ontology/precompute-layout.mjs` after edge curation.
    this.positions$ = this.http.get<PositionsPayload>(POSITIONS_URL).pipe(
      map((payload) => {
        if (!payload?.positions) return null;
        const m = new Map<string, { x: number; y: number }>();
        for (const [k, p] of Object.entries(payload.positions)) {
          if (typeof p?.x === 'number' && typeof p?.y === 'number') m.set(k, p);
        }
        return m;
      }),
      catchError(() => of(null)),
      shareReplay({ bufferSize: 1, refCount: false }),
    );
  }

  /**
   * Build the in-memory adjacency map from the consolidated payload.
   * Each edge is registered under BOTH endpoint keys (the graph is undirected).
   *
   * Edges touching an excluded (pre-release) node are dropped. Since
   * graph nodes are derived purely from edge endpoints, this removes the node
   * from every consumer (getAll/getSubgraph/getNeighborsByType) and its dangling
   * edges in one place. `excluded` is empty in dev → full author preview.
   */
  private buildIndex(
    payload: ConsolidatedOntology | null | undefined,
    excluded: Set<string> = new Set(),
  ): IndexedOntology {
    const adjacency = new Map<string, OntologyEdge[]>();
    const edges: OntologyEdge[] = [];

    if (!payload || !Array.isArray(payload.edges)) {
      return EMPTY_ONTOLOGY;
    }

    for (const e of payload.edges) {
      if (!e || !e.a || !e.b || !e.kind) continue;
      if (excluded.has(nodeKey(e.a)) || excluded.has(nodeKey(e.b))) continue;
      edges.push(e);
      const ka = nodeKey(e.a);
      const kb = nodeKey(e.b);
      const al = adjacency.get(ka);
      if (al) al.push(e);
      else adjacency.set(ka, [e]);
      const bl = adjacency.get(kb);
      if (bl) bl.push(e);
      else adjacency.set(kb, [e]);
    }

    const nodeCount: Record<OntologyNodeType, number> = {
      article: payload.nodeCount?.article ?? 0,
      demo: payload.nodeCount?.demo ?? 0,
      glossary: payload.nodeCount?.glossary ?? 0,
      timeline: payload.nodeCount?.timeline ?? 0,
      source: payload.nodeCount?.source ?? 0,
    };

    return { edges, adjacency, nodeCount };
  }

  /**
   * For a focus node, return its partners grouped by partner type.
   * The focus node is excluded from results; same-type partners include
   * themselves only through other-id matches.
   */
  getNeighborsByType(type: OntologyNodeType, id: string): Observable<Record<OntologyNodeType, OntologyNodeRef[]>> {
    return this.indexed$.pipe(
      map((idx) => {
        const focusKey = `${type}:${id}`;
        const list = idx.adjacency.get(focusKey) ?? [];
        const grouped: Record<OntologyNodeType, OntologyNodeRef[]> = {
          article: [],
          demo: [],
          glossary: [],
          timeline: [],
          source: [],
        };
        const seen = new Set<string>();
        for (const e of list) {
          const partner = nodeKey(e.a) === focusKey ? e.b : e.a;
          const pk = nodeKey(partner);
          if (pk === focusKey) continue; // defensive: skip if edge accidentally self-loops
          if (seen.has(pk)) continue;
          seen.add(pk);
          grouped[partner.type].push(partner);
        }
        return grouped;
      }),
    );
  }

  /**
   * Build a focus-subgraph: the focus node + all neighbors reachable in `hops`.
   * V1 supports hops=1 (default) and hops=2.
   */
  getSubgraph(focus: OntologyNodeRef, hops: number = 1): Observable<OntologySubgraph> {
    return this.indexed$.pipe(
      map((idx) => {
        const focusKey = nodeKey(focus);
        const visited = new Set<string>([focusKey]);
        const frontier = new Set<string>([focusKey]);
        const collectedEdges = new Map<string, OntologyEdge>();

        for (let h = 0; h < hops; h++) {
          const next = new Set<string>();
          for (const key of frontier) {
            const incident = idx.adjacency.get(key) ?? [];
            for (const e of incident) {
              const ek = `${nodeKey(e.a)}|${nodeKey(e.b)}|${e.kind}`;
              collectedEdges.set(ek, e);
              const otherKey = nodeKey(e.a) === key ? nodeKey(e.b) : nodeKey(e.a);
              if (!visited.has(otherKey)) {
                visited.add(otherKey);
                next.add(otherKey);
              }
            }
          }
          if (next.size === 0) break;
          frontier.clear();
          for (const k of next) frontier.add(k);
        }

        // Build node-list from visited keys
        const nodes: OntologyNodeRef[] = [];
        for (const key of visited) {
          const colonIdx = key.indexOf(':');
          const t = key.slice(0, colonIdx) as OntologyNodeType;
          const i = key.slice(colonIdx + 1);
          nodes.push({ type: t, id: i });
        }
        return { focus, nodes, edges: [...collectedEdges.values()] };
      }),
    );
  }

  /**
   * Pre-computed node positions for the full-graph layout. `null` if the
   * positions file is missing — callers should fall back to a live layout.
   * Result is cached for the lifetime of the service.
   */
  getPositions(): Observable<Map<string, { x: number; y: number }> | null> {
    return this.positions$;
  }

  /**
   * Returns the entire graph (all nodes from the adjacency keys, all edges).
   * Used by OntologyMapComponent in full-graph mode and /concept-map page.
   * Optionally filter nodes by type list — edges with one endpoint outside
   * the kept set are dropped automatically.
   */
  getAll(typeFilter?: OntologyNodeType[] | null): Observable<{
    nodes: OntologyNodeRef[];
    edges: OntologyEdge[];
  }> {
    return this.indexed$.pipe(
      map((idx) => {
        const wanted = typeFilter && typeFilter.length > 0 ? new Set(typeFilter) : null;
        const seen = new Set<string>();
        const nodes: OntologyNodeRef[] = [];
        const collectNode = (ref: OntologyNodeRef) => {
          if (wanted && !wanted.has(ref.type)) return false;
          const k = `${ref.type}:${ref.id}`;
          if (seen.has(k)) return true;
          seen.add(k);
          nodes.push(ref);
          return true;
        };
        const edges: OntologyEdge[] = [];
        for (const e of idx.edges) {
          const okA = collectNode(e.a);
          const okB = collectNode(e.b);
          if (okA && okB) edges.push(e);
        }
        return { nodes, edges };
      }),
    );
  }
}

// Re-export type list for callers that want it
export { ONTOLOGY_NODE_TYPES };
