/**
 * Update Detection Service
 * Handles cache busting and ensures users always get the latest version after updates
 */
import { Injectable, NgZone, PLATFORM_ID, inject } from '@angular/core';
import { isPlatformBrowser } from '@angular/common';
import { BUILD_VERSION } from '../../build-version';
import { safeStorage } from '../utils/safe-storage';
import { clearUpdateCaches } from '../utils/storage-keys';
import { NotificationService } from './notification.service';
import { NotificationEntry } from '../models/notification.model';

export interface AppVersionInfo {
  version: string;
  buildTime: string;
  hash: string;
}

@Injectable({
  providedIn: 'root',
})
export class UpdateDetectionService {
  private readonly VERSION_KEY = 'app_version';
  private readonly CHECK_INTERVAL = 5 * 60 * 1000; // Check every 5 minutes
  private readonly platformId = inject(PLATFORM_ID);
  private readonly ngZone = inject(NgZone);
  private readonly notificationService = inject(NotificationService);

  // Current app version, derived from the per-build BUILD_VERSION constant
  // (src/build-version.ts, regenerated by scripts/generate-build-version.ts on
  // every build; format '<YYYYMMDD>-<contentHash>'). This per-build value is the
  // variable input the detection relies on: a stale version persisted in
  // localStorage from an earlier build differs from the freshly-loaded bundle's
  // BUILD_VERSION, which is what makes handleUpdateDetected() fire after a deploy.
  // The previous hardcoded constant never changed across builds, so the
  // self-referential compare (stored vs constant) could never differ — the
  // mechanism was inert.
  private currentVersion: AppVersionInfo = {
    version: BUILD_VERSION,
    buildTime: BUILD_VERSION.split('-')[0],
    hash: BUILD_VERSION.split('-')[1] ?? BUILD_VERSION,
  };

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      this.initializeUpdateDetection();
    }
  }

  /**
   * Initialize update detection system
   * browser-only: the constructor calls it behind isPlatformBrowser.
   */
  private initializeUpdateDetection(): void {
    this.checkForUpdates();

    // Run outside Angular zone so setInterval doesn't block hydration/stability
    this.ngZone.runOutsideAngular(() => {
      setInterval(() => {
        this.checkForUpdates();
      }, this.CHECK_INTERVAL);

      document.addEventListener('visibilitychange', () => {
        if (!document.hidden) {
          this.checkForUpdates();
        }
      });
    });
  }

  /**
   * Check if there's a version mismatch indicating an update
   */
  private checkForUpdates(): void {
    const storedVersion = this.getStoredVersion();

    if (storedVersion && this.isVersionDifferent(storedVersion)) {
      this.handleUpdateDetected();
    } else {
      // Store current version info
      this.storeCurrentVersion();
    }
  }

  /**
   * Handle a detected update: clear caches silently in the background so the
   * next user-triggered reload (F5) fetches fresh assets. Does NOT inject any
   * news/bell notification — an earlier iteration spawned a "Neue Version
   * verfügbar" news item on every detected version change (one per
   * build/deploy), which flooded the /news feed. notifyOfUpdate() is retained
   * for unit tests but intentionally no longer called from the detection flow.
   */
  private handleUpdateDetected(): void {
    this.clearAllCaches()
      .then(() => this.storeCurrentVersion())
      .catch((error) => {
        console.warn('Failed to clear caches:', error);
        // Best-effort: at least record the new version locally so we
        // don't keep firing the same notification on every poll.
        this.storeCurrentVersion();
      });
  }

  /**
   * Push a release-type notification through NotificationService so
   * the bell counter goes up and the aria-live region announces.
   * Public so unit tests (and future manual triggers) can drive it
   * without standing up the polling/version-mismatch machinery.
   */
  public notifyOfUpdate(): void {
    const entry: NotificationEntry = {
      id: `client-update-${Date.now()}-${Math.random().toString(36).substring(2, 8)}`,
      publishedAt: new Date().toISOString(),
      type: 'release',
      titleKey: 'notifications.clientUpdate.title',
      descriptionKey: 'notifications.clientUpdate.description',
      pinned: true,
      priority: 'high',
    };
    this.notificationService.injectClientNotification(entry);
  }

  /**
   * Clear the caches a new build invalidates: Cache Storage entries and the
   * `clearOnUpdate` keys from the storage-key registry. Never user state.
   * browser-only: part of the reload flow, started from the browser-only update check.
   */
  private async clearAllCaches(): Promise<void> {
    const promises: Promise<void>[] = [];

    // Clear Service Worker caches if available
    if ('serviceWorker' in navigator && 'caches' in window) {
      promises.push(
        caches
          .keys()
          .then((cacheNames) => {
            return Promise.all(cacheNames.map((cacheName) => caches.delete(cacheName)));
          })
          .then(() => {}),
      );
    }

    // Drop only the cache keys a new build invalidates. Everything the visitor
    // chose or made — progress, theme, font, language, favorites, the feedback
    // inbox — stays. This used to be localStorage.clear() plus a restore of the
    // UserDataProvider keys, which silently erased every preference not owned by
    // a provider on each deploy. sessionStorage holds no kit keys, so it is not
    // touched either. The key list lives in utils/storage-keys.ts.
    clearUpdateCaches();

    await Promise.all(promises);
  }

  /**
   * Check if version is different from stored version
   */
  private isVersionDifferent(storedVersion: AppVersionInfo): boolean {
    return (
      storedVersion.version !== this.currentVersion.version ||
      storedVersion.hash !== this.currentVersion.hash ||
      storedVersion.buildTime !== this.currentVersion.buildTime
    );
  }

  /**
   * Get stored version info
   */
  private getStoredVersion(): AppVersionInfo | null {
    try {
      const stored = safeStorage.get(this.VERSION_KEY);
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  }

  /**
   * Store current version info
   */
  private storeCurrentVersion(): void {
    safeStorage.set(this.VERSION_KEY, JSON.stringify(this.currentVersion));
  }

  /**
   * Manually trigger update check (for debugging)
   */
  public forceUpdateCheck(): void {
    this.checkForUpdates();
  }

  /**
   * Get current version info
   */
  public getCurrentVersion(): AppVersionInfo {
    return { ...this.currentVersion };
  }
}
