#!/usr/bin/env node

/**
 * Build Version Generator
 *
 * Generates a build version hash from i18n and content bundle files.
 * The hash is used as a cache-busting query parameter (?v=<hash>)
 * when loading JSON bundles at runtime.
 *
 * Input:  src/assets/i18n/i18n.*.json + src/assets/data/content.*.json
 * Output: src/build-version.ts (gitignored, regenerated each build) — the cache-busting
 *         hash plus ANGULAR_VERSION, the resolved Angular version the UI attributes.
 *
 * Usage: node scripts/generate-build-version.ts   (Node 24's built-in type-stripping
 *        runs this .ts file directly — see package.json's generate:build-version)
 *
 * Deliberately CommonJS `require()`, not `import`: package.json has no "type" field,
 * so Node's module-type detection defaults to CommonJS for every extensionless-typed
 * file in the repo (this one included) and only falls back to ESM, with a
 * [MODULE_TYPELESS_PACKAGE_JSON] warning on every run, when it finds `import`/`export`
 * syntax it must reparse. Plain `require()` parses as CommonJS on the first pass, so
 * the fallback — and the warning — never triggers. The alternative fix (`"type": "module"` in
 * package.json) was deliberately not taken here — out of this script's scope, and a
 * repo-wide change to how every `.js` script resolves modules.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const I18N_DIR = 'src/assets/i18n';
const CONTENT_DIR = 'src/assets/data';
const OUTPUT_FILE = 'src/build-version.ts';

function collectBundleFiles(): string[] {
  const files: string[] = [];

  // i18n bundles
  if (fs.existsSync(I18N_DIR)) {
    for (const f of fs.readdirSync(I18N_DIR)) {
      if (f.startsWith('i18n.') && f.endsWith('.json')) {
        files.push(path.join(I18N_DIR, f));
      }
    }
  }

  // content bundles
  if (fs.existsSync(CONTENT_DIR)) {
    for (const f of fs.readdirSync(CONTENT_DIR)) {
      if (f.startsWith('content.') && f.endsWith('.json')) {
        files.push(path.join(CONTENT_DIR, f));
      }
    }
  }

  return files.sort();
}

function computeHash(files: string[]): string {
  const hash = crypto.createHash('sha256');
  for (const file of files) {
    hash.update(fs.readFileSync(file));
  }
  return hash.digest('hex').substring(0, 8);
}

/**
 * The Angular version this build actually runs on.
 *
 * Resolved from the installed package, not from the range in package.json: "^22.1.4"
 * is the lower bound of what npm may install, so a page that prints it is stating
 * something it does not know. It is emitted here rather than imported in the
 * component because `import { dependencies } from 'package.json'` pulls the whole
 * dependency map into the client bundle to read one string out of it.
 *
 * Falls back to the declared range (prefix stripped) when node_modules is absent —
 * that is a worse answer, but a build that fails over an attribution label would be
 * a far worse one.
 */
function resolveAngularVersion(): string {
  try {
    return require('@angular/core/package.json').version;
  } catch {
    const declared = require('../package.json').dependencies?.['@angular/core'] ?? '';
    return String(declared).replace(/^[^\d]*/, '') || 'unknown';
  }
}

function main(): void {
  const files = collectBundleFiles();

  if (files.length === 0) {
    console.warn('Warning: No bundle files found. Using fallback version.');
  }

  const date = new Date().toISOString().slice(0, 10).replace(/-/g, '');
  const hash = files.length > 0 ? computeHash(files) : '00000000';
  const version = `${date}-${hash}`;

  const angular = resolveAngularVersion();
  const content =
    `// Auto-generated by scripts/generate-build-version.ts — do not edit\n` +
    `export const BUILD_VERSION = '${version}';\n` +
    `export const ANGULAR_VERSION = '${angular}';\n`;

  fs.writeFileSync(OUTPUT_FILE, content, 'utf-8');
  console.log(`Generated build version: ${version} (from ${files.length} bundle files), Angular ${angular}`);
}

main();
